resolver: lts-17.6

packages:
- engine-registry
- engine-shared
- engine-wizard
- engine-wizard-metamodel-migrator

extra-deps:
  - vendor/bson-generic
  - vendor/mongoDB-migration
  - vendor/postgresql-migration
  - persistent-mongoDB-2.10.0.0
  - pwstore-fast-2.4.4
  - pretty-terminal-0.1.0.0
  - cron-0.7.0
  - ginger-0.10.0.5
  - text-replace-0.0.0.4
  - servant-errors-0.1.3.1
  - servant-multipart-0.11.4
  - servant-websockets-2.0.0
  - fsutils-0.1.2
  - oidc-client-0.5.0.0
  # Hack for mail
  - HaskellNet-SSL-0.3.4.1
  - github: jtdaugherty/HaskellNet
    commit: "5aa1f3b"
  - network-2.8.0.1
  - network-bsd-2.8.0.0

allow-newer: true
