name: Build

on:
  push:

jobs:
  btp:
    name: Build-Tag-Push
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        component: [registry]
    
    env:
      COMPONENT: ${{ matrix.component }}
      IMAGE_NAME: ${{ matrix.component }}-server
      PUBLIC_IMAGE_PREFIX: datastewardshipwizard
      DOCKER_META_CONTEXT: '.'
      DOCKER_META_FILE: './engine-${{ matrix.component }}/Dockerfile.build'
      DOCKER_META_PLATFORMS: 'linux/arm64'

    steps:

    - name: Checkout git repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2    
      
    - name: Update config and build info
      run: |
        ./scripts/update-file-timestamps.sh
        ./scripts/expand-example-files.sh
        ./scripts/generate-build-info.sh engine-$COMPONENT

# (4.1) -> Docker build (test)
    - name: Docker meta [test]
      id: meta-test
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ env.PUBLIC_IMAGE_PREFIX }}/${{ env.IMAGE_NAME }}
        tags: |
          type=sha

    - name: Docker build [test, build image]
      uses: docker/build-push-action@v4
      with:
        context: ${{ env.DOCKER_META_CONTEXT }}
        file: ${{ env.DOCKER_META_FILE }}
        target: 'build'
        platforms: ${{ env.DOCKER_META_PLATFORMS }}
        push: false
        tags: ${{ steps.meta-test.outputs.tags }}
        labels: ${{ steps.meta-test.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Docker build [test]
      uses: docker/build-push-action@v4
      with:
        context: ${{ env.DOCKER_META_CONTEXT }}
        file: ${{ env.DOCKER_META_FILE }}
        platforms: ${{ env.DOCKER_META_PLATFORMS }}
        push: false
        tags: ${{ steps.meta-test.outputs.tags }}
        labels: ${{ steps.meta-test.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
